<br>
<div class="main" >
   <H1>$HistoryLabels.history_tables.title</H1>
      <center>
        <div class="container" >
            <div class="col-sm-12 main" >
             <br><h3>$HistoryLabels.history_tables.min_temp</h3>
                $min_temp_table

             <br><h3>$HistoryLabels.history_tables.avg_temp</h3>
                $avg_temp_table

             <br><h3>$HistoryLabels.history_tables.max_temp</h3>
                $max_temp_table

             <br><h3>$HistoryLabels.history_tables.rain</h3>
                $rain_table

             <br><h3>$HistoryLabels.history_tables.rain_days</h3>
                $rain_days_table

             <br><h3>$HistoryLabels.history_tables.uv_max</h3>
                $uv_max_table
             </div>
        </div>
      </center>
</div>
